version: '3.9'
name: funk-finder
services:
  web:
    container_name: gcr.io/fruup/funk-finder-web
    build:
      dockerfile: .docker/web/Dockerfile
      target: prod
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    networks:
      - funk-finder

  db:
    container_name: gcr.io/fruup/funk-finder-db
    build:
      dockerfile: .docker/db/Dockerfile
    ports:
      - 8080:8080
    networks:
      - funk-finder

  scraper-job:
    container_name: gcr.io/fruup/funk-finder-scraper/job
    build:
      dockerfile: .docker/scraper/job/Dockerfile
      target: prod
    env_file:
      - scraper/.env
    networks:
      - funk-finder

  scraper-api:
    container_name: gcr.io/fruup/funk-finder-scraper/api
    build:
      dockerfile: .docker/scraper/api/Dockerfile
      target: prod
    networks:
      - funk-finder

  chroma:
    container_name: gcr.io/fruup/funk-finder-chroma
    build:
      dockerfile: .docker/chroma/Dockerfile
    networks:
      - funk-finder

networks:
  funk-finder:
    driver: bridge

volumes:
  chroma-data:
    driver: local
    driver_opts:
      type: none
      device: ./chroma/data
      o: bind
