version: '3.9'
name: funk-finder
services:
  web:
    build:
      dockerfile_inline: |
        FROM oven/bun:latest
    entrypoint: bash -c "bun i; bun dev"
    working_dir: /work/web
    ports:
      - 5173:5173
    volumes:
      - ./web:/work/web
      - ./db:/work/db:ro
      - ./scraper:/work/scraper:ro
    networks:
      - funk-finder

  db:
    build:
      dockerfile: .docker/db/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./db/pb/pb_data:/pb/pb_data
      - ./db/pb/pb_migrations:/pb/pb_migrations
    networks:
      - funk-finder

  # scraper:
  #   build:
  #     dockerfile: scraper/Dockerfile
  #     target: dev
  #   # working_dir: /work/scraper
  #   ports:
  #     - 3000:3000
  #   # expose:
  #   # - 3000
  #   volumes:
  #     - ./scraper:/work/scraper
  #     - ./db:/work/db:ro
  #   networks:
  #     - funk-finder

  scraper-api:
    build:
      dockerfile: .docker/scraper/api/Dockerfile
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./scraper:/work/scraper
    networks:
      - funk-finder

  chroma:
    build:
      dockerfile: .docker/chroma/Dockerfile
    volumes:
      - chroma-data:/chroma/chroma
    ports:
      - 8000:8000
    networks:
      - funk-finder

networks:
  funk-finder:
    driver: bridge

volumes:
  chroma-data:
    driver: local
    driver_opts:
      type: none
      device: ./chroma/data
      o: bind
