# -------------------------------
# | Deployment file for Coolify |
# -------------------------------

services:
  web:
    build:
      dockerfile: .docker/web/Dockerfile
      target: prod
      args:
        - 'SOURCE_COMMIT=${SOURCE_COMMIT}'
    healthcheck:
      test: curl --silent --fail-with-body localhost
      interval: 5m
      timeout: 5s
      retries: 5
      start_period: 30s
    labels:
      # Redirect to non-www
      - traefik.http.middlewares.redirect-to-non-www.redirectregex.regex=^https?://www\.(.*)
      - traefik.http.middlewares.redirect-to-non-www.redirectregex.replacement=https://$${1}
      - traefik.http.middlewares.redirect-to-non-www.redirectregex.permanent=true
    environment:
      - 'ORIGIN=${ORIGIN}'
      - 'PORT=80'
      - 'HOST_HEADER=${HOST_HEADER}'
      - 'PORT_HEADER=${PORT_HEADER}'
      - 'PROTOCOL_HEADER=${PROTOCOL_HEADER}'
      - 'CHROMADB_PATH=${CHROMA_PATH}'
      - 'POCKETBASE_PATH=${POCKETBASE_PATH}'
      - 'SCRAPER_PATH=${SCRAPER_PATH}'
      - 'CHROMADB_COLLECTION=${CHROMADB_COLLECTION}'
      - 'OPENAI_API_KEY=${OPENAI_API_KEY}'
      - 'EMBEDDING_MODEL=${EMBEDDING_MODEL}'
      - 'POCKETBASE_AUTH=${POCKETBASE_AUTH}'
      - 'CHROMA_AUTH=${CHROMA_AUTH}'

  db:
    build:
      dockerfile: .docker/db/Dockerfile
      target: prod
    healthcheck:
      test: curl --silent --fail-with-body localhost:8080/api/health
      interval: 5m
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - '/volumes/db:/pb/pb_data'

  chroma:
    build:
      dockerfile: .docker/chroma/Dockerfile
      args:
        CHROMA_AUTH_ENCRYPTED: ${CHROMA_AUTH_ENCRYPTED}
    healthcheck:
      test: curl --silent --fail-with-body localhost:8000/api/v1
      interval: 5m
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - '/volumes/chroma:/chroma/chroma'
    # labels:
    # - 'traefik.http.middlewares.test-auth.basicauth.users=...
    environment:
      - 'OPENAI_API_KEY=${OPENAI_API_KEY}'
      - 'CHROMA_WORKERS=${CHROMA_WORKERS}'

  scraper-job:
    build:
      dockerfile: .docker/scraper/job/Dockerfile
      target: prod
    environment:
      - 'OPENAI_API_KEY=${OPENAI_API_KEY}'
      - 'EMBEDDING_MODEL=${EMBEDDING_MODEL}'
      - 'CHROMA_PATH=${CHROMA_PATH}'
      - 'POCKETBASE_PATH=${POCKETBASE_PATH}'
      - 'SCRAPER_API_PATH=${SCRAPER_API_PATH}'
      - 'SESSION=${SESSION}'
      - 'POCKETBASE_AUTH=${POCKETBASE_AUTH}'
      - 'GCLOUD_KEY=${GCLOUD_KEY}'
      - 'CHROMA_AUTH=${CHROMA_AUTH}'

  scraper-api:
    build:
      dockerfile: .docker/scraper/api/Dockerfile
      target: prod
    healthcheck:
      test: curl --silent --fail-with-body localhost:3000
      interval: 5m
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      - 'SESSION=${SESSION}'
      - 'PORT=3000'
