version: '3.9'
name: funk-finder
services:
  # web:
  #   build:
  #     dockerfile_inline: |
  #       FROM oven/bun:slim
  #       RUN bun upgrade
  #   command: sh dev.sh
  #   working_dir: /work/web
  #   ports:
  #     - 5173:5173
  #   volumes:
  #     - ./web:/work/web

  db:
    build:
      dockerfile: db/Dockerfile
    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      - ./db/pb/pb_data:/pb/pb_data
      - ./db/pb/pb_migrations:/pb/pb_migrations
    networks:
      - funk-finder

  scraper:
    build:
      dockerfile: scraper/Dockerfile
      target: dev
    working_dir: /work/scraper
    volumes:
      - ./scraper:/work/scraper
      - ./db:/work/db:ro
    networks:
      - funk-finder

  chroma:
    build:
      dockerfile: chroma/Dockerfile
      # target: dev
    # working_dir: /work
    volumes:
      - chroma-data:/chroma/chroma
    ports:
      - 8000:8000
    networks:
      - funk-finder

networks:
  funk-finder:
    driver: bridge

volumes:
  chroma-data:
    driver: local
    driver_opts:
      type: none
      device: ./chroma/data
      o: bind
