version: '3.9'
name: funk-finder
services:
  # web:
  #   build:
  #     dockerfile_inline: |
  #       FROM oven/bun:slim
  #       RUN bun upgrade
  #   command: sh dev.sh
  #   working_dir: /work/web
  #   ports:
  #     - 5173:5173
  #   volumes:
  #     - ./web:/work/web

  db:
    build:
      dockerfile: .dev/Dockerfile.db
    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      - ./db/pb/pb_migrations:/pb/pb_migrations
    networks:
      - funk-finder

  scraper:
    build:
      dockerfile: scraper/Dockerfile
      target: dev
    working_dir: /work/scraper
    volumes:
      - ./scraper:/work/scraper
      - ./db:/work/db:ro
    ports:
      - 6499:6499
    networks:
      - funk-finder

  chroma:
    build:
      dockerfile: chroma/Dockerfile
      # target: dev
    # working_dir: /work
    # volumes:
    # - ./chroma/work:/work
    ports:
      - 8000:8000
    networks:
      - funk-finder

networks:
  funk-finder:
    driver: bridge
