name: funk-finder
services:
  web:
    ports:
      - 80:80
    environment:
      - PORT=80
      - ORIGIN=http://localhost
      - NODE_ENV=production

  db:
    ports:
      - 8080:8080
    volumes:
      - ./db/pb/pb_data:/pb/pb_data

  chroma:
    volumes:
      - ./chroma/data:/chroma/chroma
