# -------------------------------
# | Deployment file for Coolify |
# -------------------------------

services:
  web:
    build:
      dockerfile: .docker/web/Dockerfile
      target: prod
    environment:
      - 'ORIGIN=${ORIGIN}'
      - 'HOST_HEADER=${HOST_HEADER}'
      - 'PORT_HEADER=${PORT_HEADER}'
      - 'PROTOCOL_HEADER=${PROTOCOL_HEADER}'
      - 'CHROMADB_PATH=${CHROMA_PATH}'
      - 'POCKETBASE_PATH=${POCKETBASE_PATH}'
      - 'SCRAPER_PATH=${SCRAPER_PATH}'
      - 'CHROMADB_COLLECTION=${CHROMADB_COLLECTION}'
      - 'OPENAI_API_KEY=${OPENAI_API_KEY}'
      - 'EMBEDDING_MODEL=${EMBEDDING_MODEL}'
      - 'POCKETBASE_AUTH=${POCKETBASE_AUTH}'
      - 'CHROMA_AUTH=${CHROMA_AUTH}'
      - 'PORT=80'

  db:
    build:
      dockerfile: .docker/db/Dockerfile
      target: prod
    volumes:
      - '/volumes/db:/pb/pb_data'

  chroma:
    build:
      dockerfile: .docker/chroma/Dockerfile
      args:
        CHROMA_AUTH_ENCRYPTED: ${CHROMA_AUTH_ENCRYPTED}
    volumes:
      - '/volumes/chroma:/chroma/chroma'
    # labels:
    # - 'traefik.http.middlewares.test-auth.basicauth.users=...
    environment:
      - 'OPENAI_API_KEY=${OPENAI_API_KEY}'

  scraper-job:
    build:
      dockerfile: .docker/scraper/job/Dockerfile
      target: prod
    environment:
      - 'OPENAI_API_KEY=${OPENAI_API_KEY}'
      - 'EMBEDDING_MODEL=${EMBEDDING_MODEL}'
      - 'CHROMA_PATH=${CHROMA_PATH}'
      - 'POCKETBASE_PATH=${POCKETBASE_PATH}'
      - 'SCRAPER_API_PATH=${SCRAPER_API_PATH}'
      - 'SESSION=${SESSION}'
      - 'POCKETBASE_AUTH=${POCKETBASE_AUTH}'
      - 'GCLOUD_KEY=${GCLOUD_KEY}'
      - 'CHROMA_AUTH=${CHROMA_AUTH}'

  scraper-api:
    build:
      dockerfile: .docker/scraper/api/Dockerfile
      target: prod
    environment:
      - 'SESSION=${SESSION}'
      - 'PORT=3000'
