name: funk-finder
services:
  web:
    build:
      dockerfile: .docker/web/Dockerfile
      target: dev
    ports:
      - 5173:5173
    volumes:
      - ./web:/work/web
      - ./db:/work/db:ro
      - ./scraper:/work/scraper:ro
    networks:
      - funk-finder

  db:
    build:
      dockerfile: .docker/db/Dockerfile
      target: dev
    ports:
      - 8080:8080
    volumes:
      - ./db/pb/pb_data:/pb/pb_data
      - ./db/pb/pb_migrations:/pb/pb_migrations
    networks:
      - funk-finder

  scraper-job:
    build:
      dockerfile: .docker/scraper/job/Dockerfile
      target: dev
    volumes:
      - ./scraper:/work/scraper
      - ./db:/work/db:ro
    env_file:
      - scraper/.env
    networks:
      - funk-finder

  scraper-api:
    build:
      dockerfile: .docker/scraper/api/Dockerfile
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./scraper:/work/scraper
    env_file:
      - scraper/.env
    networks:
      - funk-finder

  chroma:
    build:
      dockerfile: .docker/chroma/Dockerfile
    volumes:
      - chroma-data:/chroma/chroma
    ports:
      - 8000:8000
    networks:
      - funk-finder

networks:
  funk-finder:
    driver: bridge

volumes:
  chroma-data:
    driver: local
    driver_opts:
      type: none
      device: ./chroma/data
      o: bind
