#!/bin/bash

# Build the docker image.
docker compose \
	-f docker-compose.coolify.yml \
	--env-file "$(dirname $0)/.env" \
	--env-file "web/.env" \
	--env-file "scraper/.env" \
	--env-file "chroma/.env" \
	build $1
