#!/bin/bash

# start services
docker compose \
	-f docker-compose.coolify.yml \
	-f docker-compose.production-test.yml \
	--env-file "$(dirname $0)/.env" \
	--env-file "web/.env" \
	--env-file "scraper/.env" \
	--env-file "chroma/.env" \
	up \
	web db chroma scraper-api
