name: Build containers
on:
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Build containers
        run: docker compose -f docker-compose.coolify.yml build
